# minibatch related
batch-size: 16
maxlen-in: 512
maxlen-out: 150

# optimization related
criterion: loss
early-stop-criterion: "validation/main/loss"
sortagrad: 0
opt: adadelta
epochs: 120
patience: 0

# network architecture
## encoder related
etype: vggblstm
elayers: 8
eunits: 512
eprojs: 512
subsample: "1"
dropout-rate: 0.1
## decoder related
dtype: lstm
dlayers: 1
dec-embed-dim: 512
dunits: 512
dropout-rate-decoder: 0.1
dropout-rate-embed-decoder: 0.1
## attention related
atype: location
adim: 512
aheads: 4
awin: 5
aconv-chans: 10
aconv-filts: 100
## joint network related
joint-dim: 512

# transducer related
mtlalpha: 1.0 # mtlalpha should be set to 1.0 (CTC) to use transducer
rnnt-mode: 'rnnt' # switch to 'rnnt-att' to use transducer with attention
model-module: "espnet.nets.pytorch_backend.e2e_asr_transducer:E2E"
