# minibatch related
batch-size: 24
maxlen-in: 384
maxlen-out: 150

# optimization related
criterion: loss
early-stop-criterion: "validation/main/loss"
sortagrad: 0
opt: noam
epochs: 120
patience: 0
accum-grad: 4
grad-clip: 5.0

# transformer related
transformer-lr: 10.0
transformer-warmup-steps: 8000
transformer-attn-dropout-rate-encoder: 0.4
transformer-attn-dropout-rate-decoder: 0.1

# network architecture
## encoder related
etype: transformer
transformer-input-layer: vgg2l
elayers: 9
eunits: 576
dropout-rate: 0.1
## decoder related
dtype: transformer
dlayers: 2
dec-embed-dim: 576
dunits: 576
dropout-rate-decoder: 0.1
## attention related
adim: 576
aheads: 4
## joint network related
joint-dim: 576

# transducer related
mtlalpha: 1.0 # mtlalpha should be set to 1.0 (CTC) to use transducer
rnnt-mode: 'rnnt' # switch to 'rnnt-att' to use transducer with attention
model-module: "espnet.nets.pytorch_backend.e2e_asr_transducer:E2E"
