# minibatch related
batch-size: 32
maxlen-in: 300
maxlen-out: 150

# optimization related
criterion: loss
early-stop-criterion: "validation/main/loss"
sortagrad: 0
opt: noam
epochs: 30
patience: 0
accum-grad: 4
grad-clip: 5.0

# transformer related
transformer-lr: 10.0
transformer-warmup-steps: 8000
transformer-attn-dropout-rate-encoder: 0.4

# network architecture
## encoder related
etype: transformer
transformer-input-layer: conv2d
elayers: 8
eunits: 768
dropout-rate: 0.4
## decoder related
dtype: lstm
dlayers: 1
dec-embed-dim: 768
dunits: 768
dropout-rate-decoder: 0.2
dropout-rate-embed-decoder: 0.1
## attention related
adim: 768
aheads: 4
## joint network related
joint-dim: 768

# transducer related
mtlalpha: 1.0 # mtlalpha should be set to 1.0 (CTC) to use transducer
rnnt-mode: 'rnnt' # switch to 'rnnt-att' to use transducer with attention
model-module: "espnet.nets.pytorch_backend.e2e_asr_transducer:E2E"
